### ISSUE TITLE
WorkSpaceUnusuedForDefinedPeriod being erroneously set to true

### ISSUE THREAD

**Issue by tmldot** [aws-samples/automate-reporting-on-amazon-workspaces-using-powershell#2]
Have noticed an issue where occasionally the WorkSpaceUnusuedForDefinedPeriod value is being set to TRUE even though the workspace either has been used in the defined period (60 in my case) or was created but not used yet.

Examples:
ADComPuterCreated      LastKnownUserConnectionTimestamp     WorkSpaceUnusuedForDefinedPeriod
11/21/2022 20:20             11/22/2022 17:56                                            TRUE
10/28/2022 12:14              1/1/0001 00:00:00                                          TRUE

We have a few hundred workspaces and only 32 are reporting an erroneous WorkSpaceUnusuedForDefinedPeriod value.

**Comment by awsgrant** [comment]
Region added via the other pull request
